export const DEMO_STUDENT = {
    id: 'usr_student_01',
    name: 'Demo Student',
    email: 'student@example.invalid',
    studentId: 'STU-DEMO-001',
    department: 'Computer Science & Engineering',
    semester: '6th Semester',
    role: 'student',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
};
export const DEMO_ADMIN = {
    id: 'usr_admin_01',
    name: 'Demo Administrator',
    email: 'admin@example.invalid',
    studentId: 'FAC-DEMO-001',
    department: 'Student Affairs & IT Directorate',
    semester: 'Faculty / Admin',
    role: 'admin',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
};
export const INITIAL_EVENTS = [
    {
        id: 'evt-01',
        title: 'CPCCU AI Hackathon 2026',
        description: 'The flagship annual 24-hour hackathon organized by Computer Programming & Coding Club City University. Build transformative AI applications, solve real campus challenges, and pitch to industry tech leads.',
        club: 'City University Computer Club (CUCC)',
        category: 'Competition',
        date: '2026-10-15',
        time: '09:00 AM - Next Day 09:00 AM',
        location: 'Auditorium & Innovation Lab, Permanent Campus',
        organizer: 'CUCC & Dept. of CSE',
        registrationDeadline: '2026-10-12',
        capacity: 120,
        registeredCount: 84,
        bannerImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80',
    },
    {
        id: 'evt-02',
        title: 'Inter-Department Programming Contest (IDPC)',
        description: 'Test your algorithmic problem-solving skills across 8 intense competitive programming problems. National contest scoring rules apply.',
        club: 'CU Competitive Programming Forum',
        category: 'Technical',
        date: '2026-10-20',
        time: '02:00 PM - 06:00 PM',
        location: 'Central Software Lab 4 & 5',
        organizer: 'Dept. of CSE',
        registrationDeadline: '2026-10-18',
        capacity: 90,
        registeredCount: 65,
        bannerImage: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=800&q=80',
    },
    {
        id: 'evt-03',
        title: 'Autonomous Robotics & IoT Hands-on Workshop',
        description: 'Learn Arduino, ESP32, and sensor interfacing. Build obstacle avoidance line-follower robots in small guided squads.',
        club: 'Robotics & Hardware Society',
        category: 'Workshop',
        date: '2026-10-24',
        time: '10:00 AM - 04:00 PM',
        location: 'EEE Microcontroller Lab, 3rd Floor',
        organizer: 'Robotics Club',
        registrationDeadline: '2026-10-22',
        capacity: 50,
        registeredCount: 42,
        bannerImage: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80',
    },
    {
        id: 'evt-04',
        title: 'Cyber Security & Ethical Hacking Bootcamp',
        description: 'Deep dive into penetration testing, network packet sniffing with Wireshark, OWASP Top 10 vulnerabilities, and bug bounty best practices.',
        club: 'City CyberSec Guild',
        category: 'Technical',
        date: '2026-10-28',
        time: '11:00 AM - 03:00 PM',
        location: 'Networking Lab 2',
        organizer: 'CyberSec Guild',
        registrationDeadline: '2026-10-26',
        capacity: 70,
        registeredCount: 58,
        bannerImage: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80',
    },
    {
        id: 'evt-05',
        title: 'City University National Debate Championship 2026',
        description: 'Parliamentary debate championship gathering 32 debaters from top universities. Motions covering climate economics, tech governance, and higher education.',
        club: 'City Debating Society (CDS)',
        category: 'Debate',
        date: '2026-11-02',
        time: '09:30 AM - 06:00 PM',
        location: 'Conference Hall A & B',
        organizer: 'City Debating Society',
        registrationDeadline: '2026-10-30',
        capacity: 100,
        registeredCount: 76,
        bannerImage: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=800&q=80',
    },
    {
        id: 'evt-06',
        title: 'Career Genesis: From Campus to FAANG & Local Tech Giants',
        description: 'Distinguished alumni working at Google, bKash, and Brain Station 23 share secrets on resume building, system design rounds, and HR interviews.',
        club: 'Career Guidance & Alumni Association',
        category: 'Career',
        date: '2026-11-06',
        time: '03:30 PM - 06:30 PM',
        location: 'Main Auditorium',
        organizer: 'Career Development Center (CDC)',
        registrationDeadline: '2026-11-04',
        capacity: 250,
        registeredCount: 198,
        bannerImage: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80',
    },
    {
        id: 'evt-07',
        title: 'Autumn Cultural Fiesta & Unplugged Concert',
        description: 'An evening of classical music, drama troupe performance, acoustic live music bands, and campus photography showcase.',
        club: 'City Cultural Club',
        category: 'Cultural',
        date: '2026-11-12',
        time: '04:00 PM - 09:00 PM',
        location: 'Open Amphitheatre, Campus Ground',
        organizer: 'Cultural Forum',
        registrationDeadline: '2026-11-10',
        capacity: 400,
        registeredCount: 310,
        bannerImage: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80',
    },
    {
        id: 'evt-08',
        title: 'Inter-Department Cricket Carnival 2026',
        description: 'The most anticipated turf tournament of the year. 10 teams battling over 4 days for the prestigious Vice Chancellor Trophy.',
        club: 'City Sports Club',
        category: 'Sports',
        date: '2026-11-18',
        time: '08:30 AM - 05:00 PM',
        location: 'University Sports Complex Ground',
        organizer: 'Sports Directorate',
        registrationDeadline: '2026-11-14',
        capacity: 160,
        registeredCount: 160,
        bannerImage: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=800&q=80',
    },
    {
        id: 'evt-09',
        title: 'Symposium on Machine Learning in Healthcare Research',
        description: 'Paper presentations and keynote addresses on computer vision for medical imaging and genomic sequencing algorithms.',
        club: 'Research & Innovation Wing',
        category: 'Research',
        date: '2026-11-22',
        time: '10:00 AM - 03:00 PM',
        location: 'Seminar Room 302',
        organizer: 'Faculty of Science & Engineering',
        registrationDeadline: '2026-11-19',
        capacity: 80,
        registeredCount: 39,
        bannerImage: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
    }
];
export const INITIAL_RESOURCES = [
    {
        id: 'res-01',
        title: 'CSE 321: Database Systems — Midterm & Final Previous Questions (2022-2025)',
        description: 'Comprehensive compilation of past examination papers for CSE 321 including SQL queries, normalization, ER diagram problems, and transaction management with solved answers.',
        course: 'CSE 321',
        department: 'Computer Science & Engineering',
        category: 'Previous Question',
        semester: '5th Semester',
        fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        fileSize: '4.8 MB',
        uploadedBy: 'usr_student_01',
        uploadedByName: 'Demo Student',
        createdAt: '2026-10-02',
        downloadCount: 342,
    },
    {
        id: 'res-02',
        title: 'CSE 321: MySQL & PostgreSQL Lab Experiment Manual & Solutions',
        description: 'Official laboratory guidelines containing 12 structured tasks: DDL, DML, Nested Joins, Stored Procedures, Triggers, and Indexing benchmarks.',
        course: 'CSE 321',
        department: 'Computer Science & Engineering',
        category: 'Lab Manual',
        semester: '5th Semester',
        fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        fileSize: '3.2 MB',
        uploadedBy: 'usr_admin_01',
        uploadedByName: 'Demo Administrator',
        createdAt: '2026-09-28',
        downloadCount: 289,
    },
    {
        id: 'res-03',
        title: 'CSE 415: Artificial Intelligence & Search Algorithms Lecture Notes',
        description: 'Detailed handwritten and digital lecture summaries covering A* search, Minimax with Alpha-Beta Pruning, Constraint Satisfaction, and Markov Decision Processes.',
        course: 'CSE 415',
        department: 'Computer Science & Engineering',
        category: 'Notes',
        semester: '7th Semester',
        fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        fileSize: '7.1 MB',
        uploadedBy: 'usr_student_01',
        uploadedByName: 'Demo Student',
        createdAt: '2026-10-04',
        downloadCount: 195,
    },
    {
        id: 'res-04',
        title: 'CSE 223: Data Structures & Algorithms Lab Manual (C++/Java)',
        description: 'Step-by-step implementations of Binary Search Trees, AVL Trees, Dijkstra shortest path, Prim-Kruskal MST, and Dynamic Programming templates.',
        course: 'CSE 223',
        department: 'Computer Science & Engineering',
        category: 'Lab Manual',
        semester: '3rd Semester',
        fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        fileSize: '5.4 MB',
        uploadedBy: 'usr_admin_01',
        uploadedByName: 'Demo Administrator',
        createdAt: '2026-09-15',
        downloadCount: 512,
    },
    {
        id: 'res-05',
        title: 'CSE 311: Operating Systems Final Question Bank & Solved Numericals',
        description: 'Process scheduling (SJF, Round Robin), Banker Algorithm deadlock avoidance, paging page replacement calculations (FIFO, LRU, Optimal).',
        course: 'CSE 311',
        department: 'Computer Science & Engineering',
        category: 'Previous Question',
        semester: '5th Semester',
        fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        fileSize: '3.9 MB',
        uploadedBy: 'usr_student_01',
        uploadedByName: 'Demo Student',
        createdAt: '2026-09-20',
        downloadCount: 420,
    },
    {
        id: 'res-06',
        title: 'EEE 163: Basic Electrical Engineering Formula Sheet & Notes',
        description: 'Circuit analysis theorems: Thevenin, Norton, Superposition, Maximum Power Transfer, AC sinusoidal circuit phasors, and RLC resonance.',
        course: 'EEE 163',
        department: 'Electrical & Electronic Engineering',
        category: 'Study Material',
        semester: '1st Semester',
        fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        fileSize: '2.1 MB',
        uploadedBy: 'usr_admin_01',
        uploadedByName: 'Demo Administrator',
        createdAt: '2026-08-30',
        downloadCount: 180,
    },
    {
        id: 'res-07',
        title: 'CSE 431: Computer Networks Packet Tracer Lab Assignment Guidelines',
        description: 'Subnetting VLSM design schemes, VLAN trunking, OSPF routing protocol configuration, and DNS/DHCP server setup in Cisco Packet Tracer.',
        course: 'CSE 431',
        department: 'Computer Science & Engineering',
        category: 'Assignment',
        semester: '7th Semester',
        fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        fileSize: '6.2 MB',
        uploadedBy: 'usr_admin_01',
        uploadedByName: 'Demo Administrator',
        createdAt: '2026-10-01',
        downloadCount: 234,
    },
    {
        id: 'res-08',
        title: 'MTH 201: Linear Algebra & Vector Analysis Solved Problem Sets',
        description: 'Eigenvalues, eigenvectors, matrix diagonalization, Gram-Schmidt orthogonalization, Green & Stokes theorems with solved step-by-step examples.',
        course: 'MTH 201',
        department: 'General Sciences',
        category: 'Notes',
        semester: '2nd Semester',
        fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        fileSize: '4.0 MB',
        uploadedBy: 'usr_student_01',
        uploadedByName: 'Demo Student',
        createdAt: '2026-09-10',
        downloadCount: 310,
    },
    {
        id: 'res-09',
        title: 'CSE 333: Software Engineering & Agile Scrum Sprint Template',
        description: 'SRS (Software Requirements Specification) IEEE 830 compliant template, Use Case diagrams, Class diagrams, and Jira backlog user story templates.',
        course: 'CSE 333',
        department: 'Computer Science & Engineering',
        category: 'Study Material',
        semester: '6th Semester',
        fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        fileSize: '1.9 MB',
        uploadedBy: 'usr_student_01',
        uploadedByName: 'Demo Student',
        createdAt: '2026-10-03',
        downloadCount: 175,
    },
    {
        id: 'res-10',
        title: 'BBA 101: Principles of Management Semester Final Review Kit',
        description: 'Summary of classic management theories: Taylor scientific management, Fayol administrative principles, SWOT analysis, and case study briefs.',
        course: 'BBA 101',
        department: 'Business Administration',
        category: 'Notes',
        semester: '1st Semester',
        fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        fileSize: '3.1 MB',
        uploadedBy: 'usr_student_01',
        uploadedByName: 'Demo Student',
        createdAt: '2026-09-18',
        downloadCount: 142,
    },
    {
        id: 'res-11',
        title: 'CSE 445: Machine Learning & Deep Learning Cheatsheet (PyTorch)',
        description: 'CNN architectures, Transformers self-attention mechanics, loss functions, learning rate schedulers, and PyTorch dataloader code snippets.',
        course: 'CSE 445',
        department: 'Computer Science & Engineering',
        category: 'Study Material',
        semester: '8th Semester',
        fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        fileSize: '2.8 MB',
        uploadedBy: 'usr_admin_01',
        uploadedByName: 'Demo Administrator',
        createdAt: '2026-10-05',
        downloadCount: 260,
    },
    {
        id: 'res-12',
        title: 'ENG 101: English Composition & Academic Writing Guidelines',
        description: 'APA 7th reference citation standards, persuasive essay structure, thesis statement formulating, and common grammatical pitfalls.',
        course: 'ENG 101',
        department: 'English & Humanities',
        category: 'Notes',
        semester: '1st Semester',
        fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        fileSize: '1.5 MB',
        uploadedBy: 'usr_student_01',
        uploadedByName: 'Demo Student',
        createdAt: '2026-08-25',
        downloadCount: 119,
    },
    {
        id: 'res-13',
        title: 'CSE 411: Compiler Design — Lexical Analysis & YACC Parser Manual',
        description: 'Lex specification, context-free grammars, LL(1) parse tables, LR(0)/SLR(1) item sets, and code generation intermediate quadruples.',
        course: 'CSE 411',
        department: 'Computer Science & Engineering',
        category: 'Lab Manual',
        semester: '7th Semester',
        fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        fileSize: '4.6 MB',
        uploadedBy: 'usr_admin_01',
        uploadedByName: 'Demo Administrator',
        createdAt: '2026-09-22',
        downloadCount: 198,
    },
    {
        id: 'res-14',
        title: 'PHR 205: Pharmacology I Drug Classifications & Mechanism Summary',
        description: 'Autonomic nervous system agents, adrenergic receptors, cholinergic drugs, and pharmacokinetics half-life clearance calculations.',
        course: 'PHR 205',
        department: 'Pharmacy',
        category: 'Notes',
        semester: '3rd Semester',
        fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        fileSize: '3.7 MB',
        uploadedBy: 'usr_student_01',
        uploadedByName: 'Demo Student',
        createdAt: '2026-09-12',
        downloadCount: 165,
    },
    {
        id: 'res-15',
        title: 'CSE 213: Object Oriented Programming in Java Previous Questions',
        description: 'Polymorphism, abstract classes vs interfaces, Java Generics, Multithreading synchronization, and Exception handling final questions.',
        course: 'CSE 213',
        department: 'Computer Science & Engineering',
        category: 'Previous Question',
        semester: '2nd Semester',
        fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        fileSize: '3.4 MB',
        uploadedBy: 'usr_student_01',
        uploadedByName: 'Demo Student',
        createdAt: '2026-08-19',
        downloadCount: 388,
    }
];
export const INITIAL_NOTICES = [
    {
        id: 'not-01',
        title: 'Urgent: Autumn 2026 Midterm Examination Routine & Admit Card Notice',
        description: 'All undergraduate and graduate students are hereby notified that the Midterm Examination for Autumn Semester 2026 will commence from October 25, 2026. Clearance slips and Admit Cards must be collected through the student portal before October 20.',
        category: 'Examination',
        priority: 'Urgent',
        publishedDate: '2026-10-06',
        expiryDate: '2026-10-25',
        author: 'Office of the Controller of Examinations',
    },
    {
        id: 'not-02',
        title: 'Revised Campus Shuttle Bus Schedule for Savar & Mirpur Routes',
        description: 'Due to ongoing highway expressway maintenance, the Savar-City Campus morning bus departure has been advanced by 15 minutes starting Sunday, October 11. Students are requested to check the updated schedule in CampusOS Helpdesk.',
        category: 'Transport',
        priority: 'Important',
        publishedDate: '2026-10-05',
        expiryDate: '2026-10-31',
        author: 'Transport Management Committee',
    },
    {
        id: 'not-03',
        title: 'Annual Co-Curricular Club Registration & Membership Carnival',
        description: 'Registration booths for CUCC, Debating Society, Cultural Club, Robotics Club, and Sports Club will be active at the Central Courtyard from October 12 to October 14. Freshers are strongly encouraged to join.',
        category: 'Clubs',
        priority: 'Normal',
        publishedDate: '2026-10-04',
        expiryDate: '2026-10-15',
        author: 'Directorate of Student Affairs (DSA)',
    },
    {
        id: 'not-04',
        title: 'Library Extended Hours for Final Semester Project & Research Submission',
        description: 'The Central University Library will remain open until 09:00 PM on weekdays throughout the months of October and November to facilitate capstone research and study groups.',
        category: 'Library',
        priority: 'Normal',
        publishedDate: '2026-10-01',
        expiryDate: '2026-11-30',
        author: 'Chief Librarian',
    },
    {
        id: 'not-05',
        title: 'Scholarship and Tuition Fee Waiver Application for Spring 2027',
        description: 'Merit-based and freedom-fighter quota tuition fee waiver applications are now open. Eligible students with CGPA 3.80+ must submit their authenticated grade sheets by November 15, 2026.',
        category: 'Scholarship',
        priority: 'Important',
        publishedDate: '2026-09-28',
        expiryDate: '2026-11-15',
        author: 'Registrar Office',
    }
];
export const INITIAL_BUS_ROUTES = [
    {
        id: 'bus-01',
        routeName: 'Route A — Mirpur Express',
        startingPoint: 'City University Permanent Campus',
        destination: 'Mirpur 10 (via Technical)',
        departureTime: '04:30 PM',
        arrivalTime: '05:45 PM',
        stops: ['Campus Gate 1', 'Ashulia Bridge', 'Beribadh Technical', 'Mirpur 1', 'Mirpur 10 Circle'],
        operatingDays: 'Saturday - Thursday',
        status: 'On Time',
    },
    {
        id: 'bus-02',
        routeName: 'Route B — Uttara Shuttle',
        startingPoint: 'City University Permanent Campus',
        destination: 'Uttara House Building (Sector 6)',
        departureTime: '04:45 PM',
        arrivalTime: '06:00 PM',
        stops: ['Campus Gate 1', 'Dhour Beribadh', 'Abdullahpur', 'Azampur', 'House Building'],
        operatingDays: 'Saturday - Thursday',
        status: 'On Time',
    },
    {
        id: 'bus-03',
        routeName: 'Route C — Dhanmondi & Farmgate',
        startingPoint: 'City University Permanent Campus',
        destination: 'Farmgate Overbridge',
        departureTime: '05:00 PM',
        arrivalTime: '06:30 PM',
        stops: ['Campus Gate 1', 'Gabtoli', 'Kalyanpur', 'Shyamoli', 'Asad Gate', 'Farmgate'],
        operatingDays: 'Saturday - Thursday',
        status: 'Delayed',
    },
    {
        id: 'bus-04',
        routeName: 'Route D — Savar & Nabinagar',
        startingPoint: 'City University Permanent Campus',
        destination: 'Nabinagar Smriti Soudho',
        departureTime: '04:15 PM',
        arrivalTime: '05:15 PM',
        stops: ['Campus Gate 2', 'Chandra Road', 'Savar Bus Stand', 'Cantonment Gate', 'Nabinagar'],
        operatingDays: 'Saturday - Thursday',
        status: 'On Time',
    },
    {
        id: 'bus-05',
        routeName: 'Route E — Morning Campus Inbound (Mirpur)',
        startingPoint: 'Mirpur 10 Circle',
        destination: 'City University Permanent Campus',
        departureTime: '07:15 AM',
        arrivalTime: '08:30 AM',
        stops: ['Mirpur 10', 'Mirpur 1', 'Technical', 'Ashulia Beribadh', 'Campus Gate 1'],
        operatingDays: 'Saturday - Thursday',
        status: 'On Time',
    }
];
export const INITIAL_LOST_FOUND = [
    {
        id: 'lf-01',
        type: 'Lost',
        title: 'Casio fx-991EX Scientific Calculator',
        description: 'Black calculator with a small white sticker on the back cover saying "Tanvir-CSE". Left behind in Room 402 after the CSE 321 class on Tuesday afternoon.',
        category: 'Electronics',
        location: 'Academic Building 2, Room 402',
        date: '2026-10-06',
        contactMethod: 'Phone: demo contact / Messenger: @campus_demo',
        imageUrl: 'https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd?auto=format&fit=crop&w=600&q=80',
        resolved: false,
        userId: 'usr_student_01',
        userName: 'Demo Student',
        createdAt: '2026-10-06T14:30:00Z',
    },
    {
        id: 'lf-02',
        type: 'Found',
        title: 'City University Student ID Card (BBA Department)',
        description: 'Found a student plastic ID card belonging to Demo Student 2, ID: STU-DEMO-002, near the campus cafeteria table #4.',
        category: 'ID / Documents',
        location: 'Main Cafeteria, Ground Floor',
        date: '2026-10-06',
        contactMethod: 'Left with Security Guard Post at Gate 1',
        imageUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=600&q=80',
        resolved: false,
        userId: 'usr_student_02',
        userName: 'Rakib Hasan',
        createdAt: '2026-10-06T16:15:00Z',
    },
    {
        id: 'lf-03',
        type: 'Lost',
        title: 'Blue Dell 65W Type-C Laptop Charger',
        description: 'Left in Central Library study carrel on 2nd floor near the window row around 4 PM.',
        category: 'Electronics',
        location: 'Central Library, 2nd Floor',
        date: '2026-10-05',
        contactMethod: 'WhatsApp: demo contact',
        imageUrl: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=600&q=80',
        resolved: false,
        userId: 'usr_student_03',
        userName: 'Nusrat Zahan',
        createdAt: '2026-10-05T17:00:00Z',
    },
    {
        id: 'lf-04',
        type: 'Found',
        title: 'Set of Keys with a Silver Iron Man Keychain',
        description: 'Found 3 keys attached to a metallic Marvel keychain on the basketball court bench.',
        category: 'Keys & Accessories',
        location: 'Outdoor Basketball Ground',
        date: '2026-10-04',
        contactMethod: 'Contact DSA Office desk room 104',
        imageUrl: 'https://images.unsplash.com/photo-1582139329536-e7284fece509?auto=format&fit=crop&w=600&q=80',
        resolved: true,
        userId: 'usr_admin_01',
        userName: 'Campus Security',
        createdAt: '2026-10-04T12:00:00Z',
    },
    {
        id: 'lf-05',
        type: 'Lost',
        title: 'Brown Leather Spiral Notebook with CSE 415 Project Notes',
        description: 'A brown hardbound notebook containing high-priority semester project diagrams and group notes. Critical for submission.',
        category: 'Books & Stationery',
        location: 'Academic Building 1, 3rd Floor Hallway',
        date: '2026-10-03',
        contactMethod: 'Email: student@example.invalid',
        resolved: false,
        userId: 'usr_student_01',
        userName: 'Demo Student',
        createdAt: '2026-10-03T18:00:00Z',
    }
];
export const INITIAL_COMPLAINTS = [
    {
        id: 'cmp-01',
        userId: 'usr_student_01',
        userName: 'Demo Student',
        studentId: 'STU-DEMO-001',
        category: 'Facilities & WiFi',
        subject: 'High-latency and connection drops on 4th Floor CS Lab Wi-Fi',
        description: 'The access point "CityUni-Student-Lab4" frequently disconnects during practical exams, causing loss of unsaved code during automated judge tests.',
        location: 'Building 2, Lab 4 & Lab 5',
        status: 'In Progress',
        adminNote: 'IT Network engineer dispatched on Oct 6 to replace the PoE switch and configure load balancing.',
        createdAt: '2026-10-03T10:15:00Z',
        updatedAt: '2026-10-06T11:00:00Z',
    },
    {
        id: 'cmp-02',
        userId: 'usr_student_01',
        userName: 'Demo Student',
        studentId: 'STU-DEMO-001',
        category: 'Transport',
        subject: 'Mirpur Route Bus #2 departing 10 minutes prior to scheduled departure',
        description: 'Students getting out of 4:15 PM classes missed the 4:30 PM bus because the driver drove off at 4:20 PM on Monday.',
        location: 'Campus Bus Bay 1',
        status: 'Under Review',
        adminNote: 'Notice issued to Transport supervisor to ensure strict departure timings.',
        createdAt: '2026-10-05T17:30:00Z',
        updatedAt: '2026-10-06T09:00:00Z',
    },
    {
        id: 'cmp-03',
        userId: 'usr_student_02',
        userName: 'Kamrul Islam',
        studentId: 'STU-DEMO-003',
        category: 'Cafeteria & Hygiene',
        subject: 'Water dispenser filter replacement required in Cafeteria Block B',
        description: 'The drinking water cooler indicator shows red filter status and water temperature is abnormal.',
        location: 'Central Cafeteria Block B',
        status: 'Resolved',
        adminNote: 'New multi-stage RO filter replaced and sanitized on Oct 5.',
        createdAt: '2026-10-01T12:00:00Z',
        updatedAt: '2026-10-05T15:00:00Z',
    }
];
export const INITIAL_FAQS = [
    {
        id: 'faq-01',
        question: 'What buses are available and where do they depart from?',
        answer: 'City University operates regular student shuttle buses on 5 primary routes: Mirpur Express (4:30 PM), Uttara Shuttle (4:45 PM), Dhanmondi-Farmgate (5:00 PM), Savar-Nabinagar (4:15 PM), and morning inbound buses starting at 7:15 AM. All evening buses depart from Campus Bus Bays 1 & 2.',
        category: 'Transport',
    },
    {
        id: 'faq-02',
        question: 'What time is the next bus departing?',
        answer: 'The next scheduled evening shuttle is the Mirpur Express departing at 4:30 PM from Campus Gate 1 bus bay, followed by Uttara Shuttle at 4:45 PM and Farmgate at 5:00 PM.',
        category: 'Transport',
    },
    {
        id: 'faq-03',
        question: 'Where can I find previous question papers and notes for CSE courses?',
        answer: 'You can discover, search, and download verified previous questions, lab manuals, and lecture notes directly in the Resource Hub (/resources). Filter by Department (e.g. CSE) and Course code (e.g. CSE 321).',
        category: 'Academics',
    },
    {
        id: 'faq-04',
        question: 'How do I register for an event or club contest on CampusOS?',
        answer: 'Navigate to the Events page (/events), browse through upcoming technical, cultural, or sports activities, open the event details, and click "Register Now". You will instantly receive a unique digital registration QR code.',
        category: 'Events',
    },
    {
        id: 'faq-05',
        question: 'What active student clubs are available at City University?',
        answer: 'City University hosts several active student organizations: City University Computer Club (CUCC), Robotics & Hardware Society, City Debating Society (CDS), CyberSec Guild, City Cultural Club, Sports Club, and the Career Development Center (CDC).',
        category: 'Clubs',
    },
    {
        id: 'faq-06',
        question: 'Where can I report a lost or found item?',
        answer: 'Visit the Lost & Found section (/lost-found) and click "Report Item". Specify whether it was lost or found, provide the location, time, and contact info. Items can be marked resolved once returned.',
        category: 'Services',
    },
    {
        id: 'faq-07',
        question: 'How do I submit an official campus grievance or complaint?',
        answer: 'Use the Complaint Box (/complaints) to submit grievances regarding facilities, transport, IT/Wi-Fi, or cafeterias. CampusOS provides a real-time 4-stage tracking timeline (Submitted -> Under Review -> In Progress -> Resolved).',
        category: 'Services',
    },
    {
        id: 'faq-08',
        question: 'What are the library operating hours?',
        answer: 'The Central Library is open Saturday through Thursday from 8:30 AM to 6:00 PM, with extended hours until 9:00 PM during midterm and final exam revision weeks.',
        category: 'Facilities',
    },
    {
        id: 'faq-09',
        question: 'What is the minimum attendance requirement for sitting in final exams?',
        answer: 'According to City University academic regulations, students are required to maintain a minimum of 75% class attendance to be eligible for final examinations without special senate waiver.',
        category: 'Rules',
    },
    {
        id: 'faq-10',
        question: 'How can I apply for a tuition fee waiver or merit scholarship?',
        answer: 'Merit scholarship applications are announced by the Registrar Office before the start of each semester for students securing a semester GPA of 3.80 or above. Look for notices tagged "Scholarship" in the Notices section.',
        category: 'Scholarship',
    }
];
export const INITIAL_REGISTRATIONS = [
    {
        id: 'reg-01',
        eventId: 'evt-01',
        userId: 'usr_student_01',
        registrationCode: 'CU-AI-8291',
        checkedIn: false,
        registeredAt: '2026-10-06T10:00:00Z',
        userName: 'Demo Student',
        userStudentId: 'STU-DEMO-001',
    },
    {
        id: 'reg-02',
        eventId: 'evt-06',
        userId: 'usr_student_01',
        registrationCode: 'CU-CAR-4309',
        checkedIn: true,
        checkedInAt: '2026-10-06T15:30:00Z',
        registeredAt: '2026-10-05T09:12:00Z',
        userName: 'Demo Student',
        userStudentId: 'STU-DEMO-001',
    }
];
