"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import { createClient } from "@/lib/supabase/client";
import { Trash2 } from "lucide-react";
const bucket="campus-lost-found";

export function LostFoundBoard({items,query,type,status,userId,error}) {
  const router=useRouter();const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [formError,setFormError]=useState("");
  async function createPost(event){event.preventDefault();const formElement=event.currentTarget;setBusy(true);setFormError("");setMessage("");const form=new FormData(formElement);const file=form.get("photo");const values={item_type:String(form.get("item_type")),title:String(form.get("title")||"").trim(),description:String(form.get("description")||"").trim(),location:String(form.get("location")||"").trim(),item_date:String(form.get("item_date")),contact_information:String(form.get("contact_information")||"").trim(),created_by:userId};let path="";
    try{const supabase=createClient();if(file instanceof File&&file.size){if(file.size>5*1024*1024)throw new Error("Photo must be 5 MB or smaller.");const allowed={"image/jpeg":"jpg","image/png":"png","image/webp":"webp"};if(!allowed[file.type])throw new Error("Choose a JPG, PNG, or WEBP photo.");const bytes=new Uint8Array(await file.slice(0,12).arrayBuffer());const valid=file.type==="image/jpeg"?bytes[0]===255&&bytes[1]===216:file.type==="image/png"?[137,80,78,71,13,10,26,10].every((byte,index)=>bytes[index]===byte):new TextDecoder().decode(bytes.slice(0,4))==="RIFF"&&new TextDecoder().decode(bytes.slice(8,12))==="WEBP";if(!valid)throw new Error("The photo content does not match its file type.");path=`${userId}/${crypto.randomUUID()}.${allowed[file.type]}`;const {error:uploadError}=await supabase.storage.from(bucket).upload(path,file,{contentType:file.type,upsert:false});if(uploadError)throw uploadError;values.storage_path=path;}
      const {error:insertError}=await supabase.from("lost_found_items").insert(values);if(insertError)throw insertError;formElement.reset();setMessage("Your Lost & Found post was published.");router.refresh();
    }catch(caught){if(path)await createClient().storage.from(bucket).remove([path]);setFormError(caught.message||"Your post could not be created.");}finally{setBusy(false);}}
  async function resolve(item){if(!window.confirm(`Mark “${item.title}” as resolved?`))return;setBusy(true);setFormError("");try{const {error:updateError}=await createClient().from("lost_found_items").update({status:"resolved"}).eq("id",item.id);if(updateError)throw updateError;setMessage("Item marked resolved.");router.refresh();}catch(caught){setFormError(caught.message||"Could not update this post.");}finally{setBusy(false);}}
  async function remove(item){if(!window.confirm(`Delete your post “${item.title}”?`))return;setBusy(true);setFormError("");try{const supabase=createClient();const {error:deleteError}=await supabase.from("lost_found_items").delete().eq("id",item.id);if(deleteError)throw deleteError;const {error:photoError}=item.storage_path?await supabase.storage.from(bucket).remove([item.storage_path]):{error:null};setMessage(photoError?"Your post was deleted, but its photo could not be removed.":"Your post was deleted.");router.refresh();}catch(caught){setFormError(caught.message||"The post could not be deleted.");}finally{setBusy(false);}}
  return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-7"><a href="/dashboard" className="text-xs text-[#762c3a]">Campus Pulse</a><h1 className="mt-4 text-3xl font-semibold text-[#202a35]">Lost &amp; Found</h1><p className="mt-2 text-sm text-[#697681]">Share a lost item or help return something found around campus.</p>{message&&<p role="status" className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900">{message}</p>}{formError&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-800">{formError}</p>}
    <details className="mt-5 rounded-2xl border border-[#e8e8e4] bg-white p-5"><summary className="cursor-pointer font-semibold text-[#762c3a]">Create a Lost &amp; Found post</summary><form onSubmit={createPost} className="mt-4 space-y-3"><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs">Post type<select name="item_type" className="mt-1 h-11 w-full rounded-lg border bg-white px-3 text-sm"><option value="lost">I lost an item</option><option value="found">I found an item</option></select></label><label className="text-xs">Item name<input name="title" required minLength={4} maxLength={160} className="mt-1 h-11 w-full rounded-lg border px-3 text-sm"/></label><label className="text-xs">Location<input name="location" required minLength={2} maxLength={180} placeholder="Building, room, or campus area" className="mt-1 h-11 w-full rounded-lg border px-3 text-sm"/></label><label className="text-xs">Date<input name="item_date" type="date" required max={new Date().toISOString().slice(0,10)} className="mt-1 h-11 w-full rounded-lg border px-3 text-sm"/></label></div><label className="block text-xs">Description<textarea name="description" required minLength={10} maxLength={3000} rows={3} className="mt-1 w-full rounded-lg border p-3 text-sm"/></label><label className="block text-xs">Contact / claim information<textarea name="contact_information" required minLength={3} maxLength={500} rows={2} placeholder="How should someone contact you? Avoid sharing sensitive information." className="mt-1 w-full rounded-lg border p-3 text-sm"/></label><label className="block text-xs">Photo (optional)<input name="photo" type="file" accept="image/jpeg,image/png,image/webp" className="mt-1 block w-full text-xs"/><span className="text-[10px] text-[#899198]">JPG, PNG, or WEBP · up to 5 MB</span></label><button disabled={busy} className="min-h-11 rounded-xl bg-[#762c3a] px-5 text-sm font-semibold text-white disabled:opacity-50">{busy?"Publishing…":"Publish post"}</button></form></details>
    <form action="/lost-found" className="mt-6 grid gap-2 sm:grid-cols-[1fr_150px_150px_auto]"><label><span className="sr-only">Search items</span><input name="q" defaultValue={query} placeholder="Search item or location…" className="h-11 w-full rounded-lg border bg-white px-3 text-sm"/></label><select aria-label="Post type" name="type" defaultValue={type} className="h-11 rounded-lg border bg-white px-3 text-sm"><option value="">All types</option><option value="lost">Lost</option><option value="found">Found</option></select><select aria-label="Status" name="status" defaultValue={status} className="h-11 rounded-lg border bg-white px-3 text-sm"><option value="open">Open</option><option value="resolved">Resolved</option><option value="">All statuses</option></select><button className="h-11 rounded-lg bg-[#762c3a] px-5 text-sm font-semibold text-white">Search</button></form>
    {error?<p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-800">{error}</p>:items.length?<ul className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{items.map(item=><li key={item.id} className="overflow-hidden rounded-2xl border border-[#e8e8e4] bg-white">{(item.photo_signed_url||item.photo_url)&&<Image src={item.photo_signed_url||item.photo_url} alt={`Photo of ${item.title}`} width={720} height={480} unoptimized className="h-48 w-full object-cover"/>}<div className="p-4"><div className="flex justify-between gap-2"><span className="rounded-full bg-[#f6f1ef] px-2.5 py-1 text-[10px] font-semibold uppercase text-[#762c3a]">{item.item_type}</span><span className="text-[10px] capitalize text-[#697681]">{item.status}</span></div><h2 className="mt-3 font-semibold text-[#26313a]">{item.title}</h2><p className="mt-1 whitespace-pre-wrap text-xs leading-5 text-[#697681]">{item.description}</p><p className="mt-3 text-xs font-medium text-[#414c55]">{item.location} · {new Date(`${item.item_date}T12:00:00`).toLocaleDateString("en",{dateStyle:"medium"})}</p><p className="mt-2 text-xs text-[#697681]">{item.contact_information}</p>{item.created_by===userId&&<div className="mt-4 flex gap-2">{item.status==="open"&&<button type="button" disabled={busy} onClick={()=>resolve(item)} className="rounded-lg border border-[#e1d5d6] px-3 py-2 text-xs font-semibold text-[#762c3a] disabled:opacity-50">Mark resolved</button>}<button type="button" disabled={busy} onClick={()=>remove(item)} aria-label={`Delete post ${item.title}`} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-semibold text-red-700 disabled:opacity-50"><Trash2 size={13}/>Delete post</button></div>}</div></li>)}</ul>:<div className="mt-5 rounded-2xl border border-dashed border-[#deded9] bg-white p-10 text-center text-sm text-[#697681]">No matching open posts yet. Use the form above to publish one.</div>}
  </main>;
}
