import { CalendarDays, Search, UsersRound } from "lucide-react";
import { EventCard } from "@/components/events/event-card";
import Link from "next/link";

export function EventsFeed({ events, clubs, filters, error, clubsError, isManager }) {
    return (
        <main className="mx-auto max-w-7xl px-4 pb-12 pt-7 sm:px-7 sm:pt-9 xl:px-10">
            <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#a13e4c]">Take part in campus life</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-[#202a35]">Events</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#697681]">Browse upcoming City University events and RSVP to the ones you want to join.</p></div><div className="flex flex-wrap gap-2"><a href="/my-events" className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-[#e5e3de] bg-white px-3.5 text-xs font-semibold text-[#4d5861]"><CalendarDays size={15} />My Events</a>{isManager && <a href="/manage/events" className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-[#c8102e] px-3.5 text-xs font-semibold text-white"><UsersRound size={15} />Manage events</a>}</div></div>
            {clubsError && <p role="status" className="mb-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900">Club filter options could not load.</p>}
            <p className="mb-4 rounded-xl border border-sky-200 bg-sky-50 p-3 text-xs leading-5 text-sky-950">Events currently shown are CampusOS demonstration examples, not confirmed City University schedules. Check the <a href="https://www.cityuniversity.ac.bd/all-notice" target="_blank" rel="noreferrer" className="font-semibold underline underline-offset-2">official university notices</a> for real dates and announcements.</p>
            {error && <div role="alert" className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950">{error}</div>}
            <form action="/events" method="get" className="rounded-2xl border border-[#e9e9e5] bg-white p-4 sm:p-5">
                <div className="flex flex-col gap-2 sm:flex-row"><label className="flex min-h-12 min-w-0 flex-1 items-center gap-3 rounded-xl border border-[#e2e0da] px-3.5 focus-within:border-[#a54756] focus-within:ring-2 focus-within:ring-[#c8102e]/10"><Search size={17} className="shrink-0 text-[#8a9297]" aria-hidden="true" /><span className="sr-only">Search events</span><input name="q" defaultValue={filters.search} maxLength={120} placeholder="Search event, description, or club" className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-[#92999e]" /></label><button type="submit" className="min-h-11 shrink-0 rounded-xl bg-[#c8102e] px-5 text-xs font-semibold text-white transition-colors hover:bg-[#a50e26]">Search events</button></div>
                <div className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-[1fr_1fr_1fr_1fr_auto_auto]">
                    <label className="text-[10px] font-semibold uppercase tracking-wide text-[#858d92]">Club or organizer<select name="club" defaultValue={filters.club} className="mt-1.5 min-h-10 w-full rounded-lg border border-[#e5e3de] bg-white px-3 text-xs font-normal normal-case tracking-normal text-[#37414a]"><option value="">All clubs</option>{clubs.map((club) => <option key={club.id} value={club.id}>{club.name}</option>)}</select></label>
                    <label className="text-[10px] font-semibold uppercase tracking-wide text-[#858d92]">Event type<select name="type" defaultValue={filters.type} className="mt-1.5 min-h-10 w-full rounded-lg border border-[#e5e3de] bg-white px-3 text-xs font-normal normal-case tracking-normal text-[#37414a]"><option value="">All event types</option>{["Technical", "Academic", "Cultural", "Sports", "Career", "Workshop", "Community", "Other"].map((type) => <option key={type}>{type}</option>)}</select></label>
                    <label className="text-[10px] font-semibold uppercase tracking-wide text-[#858d92]">From date<input name="from" type="date" defaultValue={filters.from} className="mt-1.5 min-h-10 w-full rounded-lg border border-[#e5e3de] bg-white px-3 text-xs font-normal normal-case tracking-normal text-[#37414a]" /></label>
                    <label className="text-[10px] font-semibold uppercase tracking-wide text-[#858d92]">Through date<input name="to" type="date" defaultValue={filters.to} min={filters.from || undefined} className="mt-1.5 min-h-10 w-full rounded-lg border border-[#e5e3de] bg-white px-3 text-xs font-normal normal-case tracking-normal text-[#37414a]" /></label>
                    <button type="submit" className="mt-auto min-h-10 rounded-lg border border-[#e5e3de] px-4 text-xs font-medium text-[#4d5861] hover:bg-[#f8f7f4]">Apply filters</button>
                    {(filters.search || filters.club || filters.type || filters.from || filters.to) && <Link href="/events" className="mt-auto inline-flex min-h-10 items-center justify-center rounded-lg px-3 text-xs text-[#c8102e]">Clear</Link>}
                </div>
            </form>
            <div className="mt-7 flex items-center justify-between"><div><h2 className="text-base font-semibold text-[#202a35]">Upcoming events</h2><p className="mt-1 text-xs text-[#7b858d]">{events.length} event{events.length === 1 ? "" : "s"} found</p></div></div>
            {events.length ? <div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{events.map((event) => <EventCard key={event.id} event={event} />)}</div> : !error && <section className="mt-4 rounded-2xl border border-dashed border-[#deded9] bg-white px-5 py-10 text-center"><span className="mx-auto grid size-12 place-items-center rounded-2xl bg-[#f6f2ee] text-[#c8102e]"><CalendarDays size={21} /></span><h2 className="mt-4 text-base font-semibold text-[#202a35]">{filters.search || filters.club || filters.type || filters.from || filters.to ? "No events match these filters" : "No upcoming events yet"}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-relaxed text-[#73808a]">Try changing your search, or check back when City University clubs publish their next events.</p></section>}
        </main>
    );
}
