import Link from "next/link";
import { Bell, Search } from "lucide-react";

export function NoticesList({ notices, query, category, error }) {
  return <main className="mx-auto max-w-5xl px-4 py-8 sm:px-7"><div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><Link href="/dashboard" className="text-xs text-[#762c3a]">Campus Pulse</Link><p className="mt-4 text-[10px] font-bold uppercase tracking-[.16em] text-[#8b6970]">City University updates</p><h1 className="mt-1 text-3xl font-semibold text-[#202a35]">Notices</h1></div><Link href="/admin/notices" className="rounded-xl border border-[#e3e3de] bg-white px-4 py-2.5 text-xs font-semibold text-[#762c3a]">Manage notices</Link></div>
    <form action="/notices" className="mb-5 grid gap-2 rounded-2xl border border-[#e8e8e4] bg-white p-3 sm:grid-cols-[1fr_180px_auto]"><label className="relative"><span className="sr-only">Search notices</span><Search size={16} className="absolute left-3 top-3 text-[#899198]"/><input name="q" defaultValue={query} placeholder="Search notices…" className="h-10 w-full rounded-lg border border-[#e3e3de] pl-9 pr-3 text-sm outline-none focus:border-[#762c3a]"/></label><label><span className="sr-only">Filter by category</span><select name="category" defaultValue={category} className="h-10 w-full rounded-lg border border-[#e3e3de] bg-white px-3 text-sm"><option value="">All categories</option>{["Academic","Exams","Registration","Campus","Events","General"].map(item=><option key={item}>{item}</option>)}</select></label><button className="h-10 rounded-lg bg-[#762c3a] px-5 text-sm font-semibold text-white">Filter</button></form>
    {error?<p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</p>:notices.length?<ul className="space-y-3">{notices.map(notice=><li key={notice.id}><Link href={`/notices/${notice.id}`} className="block rounded-2xl border border-[#e8e8e4] bg-white p-5 hover:border-[#d6bdc1]"><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-[10px] font-semibold uppercase tracking-wide text-[#762c3a]">{notice.category}</span><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold uppercase ${notice.priority==="urgent"?"bg-red-50 text-red-800":notice.priority==="important"?"bg-amber-50 text-amber-900":"bg-[#f4f2ee] text-[#68737b]"}`}><Bell size={12} className="mr-1 inline"/>{notice.priority}</span></div><h2 className="mt-2 text-base font-semibold text-[#26313a]">{notice.title}</h2><p className="mt-1 line-clamp-2 text-sm leading-6 text-[#697681]">{notice.description}</p><time className="mt-3 block text-[11px] text-[#92999e]">{new Date(notice.published_date).toLocaleDateString("en",{year:"numeric",month:"long",day:"numeric",timeZone:"Asia/Dhaka"})}</time></Link></li>)}</ul>:<div className="rounded-2xl border border-dashed border-[#deded9] bg-white p-10 text-center"><Bell className="mx-auto text-[#9b8589]"/><h2 className="mt-3 text-sm font-semibold text-[#303a43]">No notices to show</h2><p className="mt-1 text-xs text-[#79838c]">Published university notices will appear here.</p></div>}
  </main>;
}
