"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
const categories=["Academic","Exams","Registration","Campus","Events","General"];

export function NoticeAdmin({notices}) {
  const router=useRouter(); const [editing,setEditing]=useState(null); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  async function save(event) {
    event.preventDefault(); setBusy(true); setError(""); setMessage(""); const form=new FormData(event.currentTarget); const values={title:String(form.get("title")||"").trim(),category:String(form.get("category")||""),description:String(form.get("description")||"").trim(),priority:String(form.get("priority")||"normal"),is_published:form.get("is_published")==="on",published_date:form.get("published_date")?new Date(String(form.get("published_date"))).toISOString():new Date().toISOString()};
    try {const supabase=createClient(); const {data:{user},error:authError}=await supabase.auth.getUser(); if(authError||!user) throw new Error("Sign in again to manage notices."); const request=editing?supabase.from("notices").update(values).eq("id",editing.id):supabase.from("notices").insert({...values,created_by:user.id}); const {error:saveError}=await request; if(saveError) throw saveError; setEditing(null); setMessage(editing?"Notice updated.":"Notice published."); router.refresh();}
    catch(caught){setError(caught.message||"Notice could not be saved.");} finally{setBusy(false);}
  }
  async function remove(notice){if(!window.confirm(`Delete “${notice.title}”?`))return; setBusy(true);setError("");try{const {error:deleteError}=await createClient().from("notices").delete().eq("id",notice.id);if(deleteError)throw deleteError;setMessage("Notice deleted.");router.refresh();}catch(caught){setError(caught.message||"Notice could not be deleted.");}finally{setBusy(false);}}
  return <div className="mx-auto max-w-5xl px-4 py-8 sm:px-7"><a href="/dashboard" className="text-xs text-[#762c3a]">Campus Pulse</a><h1 className="mt-4 text-3xl font-semibold text-[#202a35]">Manage notices</h1><p className="mt-2 text-sm text-[#697681]">Create, update, and remove official campus notices.</p>{error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}{message&&<p role="status" className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900">{message}</p>}
    <form onSubmit={save} className="mt-6 space-y-4 rounded-2xl border border-[#e8e8e4] bg-white p-5"><h2 className="font-semibold">{editing?"Edit notice":"Create a notice"}</h2><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs">Title<input name="title" required minLength={4} maxLength={180} defaultValue={editing?.title||""} className="mt-1 block h-11 w-full rounded-lg border px-3 text-sm"/></label><label className="text-xs">Category<select name="category" defaultValue={editing?.category||"General"} className="mt-1 block h-11 w-full rounded-lg border bg-white px-3 text-sm">{categories.map(value=><option key={value}>{value}</option>)}</select></label><label className="text-xs">Priority<select name="priority" defaultValue={editing?.priority||"normal"} className="mt-1 block h-11 w-full rounded-lg border bg-white px-3 text-sm"><option value="normal">Normal</option><option value="important">Important</option><option value="urgent">Urgent</option></select></label><label className="text-xs">Publish date/time<input type="datetime-local" name="published_date" defaultValue={editing?new Date(new Date(editing.published_date).getTime()-new Date(editing.published_date).getTimezoneOffset()*60000).toISOString().slice(0,16):""} className="mt-1 block h-11 w-full rounded-lg border px-3 text-sm"/></label></div><label className="block text-xs">Details<textarea name="description" required minLength={10} maxLength={8000} defaultValue={editing?.description||""} rows={5} className="mt-1 w-full rounded-lg border p-3 text-sm"/></label><label className="flex items-center gap-2 text-xs"><input type="checkbox" name="is_published" defaultChecked={editing?editing.is_published:true}/> Published</label><div className="flex flex-wrap gap-2"><button disabled={busy} className="min-h-10 rounded-lg bg-[#762c3a] px-4 text-sm font-semibold text-white disabled:opacity-50">{busy?"Saving…":editing?"Save changes":"Publish notice"}</button>{editing&&<button type="button" onClick={()=>setEditing(null)} className="min-h-10 rounded-lg border px-4 text-sm">Cancel edit</button>}</div></form>
    <h2 className="mt-8 text-lg font-semibold">All notices</h2><ul className="mt-3 space-y-2">{notices.map(notice=><li key={notice.id} className="flex flex-wrap items-center gap-3 rounded-xl border bg-white p-4"><div className="min-w-0 flex-1"><b className="block truncate text-sm">{notice.title}</b><span className="text-xs text-[#75808a]">{notice.category} · {notice.priority} · {notice.is_published?"Published":"Draft"}</span></div><button type="button" onClick={()=>{setEditing(notice);setMessage("");}} className="text-xs font-semibold text-[#762c3a]">Edit</button><button type="button" disabled={busy} onClick={()=>remove(notice)} className="text-xs font-semibold text-red-700">Delete</button></li>)}</ul>{!notices.length&&<p className="mt-3 rounded-xl border border-dashed p-6 text-sm text-[#697681]">No notices have been created.</p>}</div>;
}
