"use client";
import { useState } from "react";
import { Sparkles } from "lucide-react";

export function NoticeSummarizer({noticeId}){
  const [summary,setSummary]=useState(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  async function summarize(){setBusy(true);setError("");setSummary(null);try{const response=await fetch(`/api/notices/${noticeId}/summarize`,{method:"POST"});const data=await response.json();if(!response.ok)throw new Error(data.error||"The notice could not be summarized.");setSummary(data);}catch(caught){setError(caught.message||"AI summarization is temporarily unavailable.");}finally{setBusy(false);}}
  return <section className="mt-7 rounded-2xl border border-[#e9e2dd] bg-[#fbf8f5] p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 text-sm font-semibold text-[#303a43]"><Sparkles size={16} className="text-[#762c3a]"/>Need the key points?</h2><p className="mt-1 text-xs text-[#697681]">AI summary of this notice. The original notice remains the source of truth.</p></div><button type="button" onClick={summarize} disabled={busy} className="min-h-10 rounded-lg bg-[#762c3a] px-4 text-xs font-semibold text-white disabled:opacity-60">{busy?"Summarizing…":"Summarize with AI"}</button></div>{busy&&<p role="status" className="mt-3 text-xs text-[#697681]">Reading the notice…</p>}{error&&<p role="alert" className="mt-3 rounded-lg bg-red-50 p-3 text-xs text-red-800">{error}</p>}{summary&&<div aria-live="polite" className="mt-4 space-y-3 border-t border-[#e5ddd7] pt-4 text-sm"><div><h3 className="text-[10px] font-bold uppercase tracking-wide text-[#8b6970]">Short summary</h3><p className="mt-1 leading-6 text-[#37414a]">{summary.short_summary}</p></div><div className="grid gap-3 sm:grid-cols-2"><div><h3 className="text-[10px] font-bold uppercase tracking-wide text-[#8b6970]">Important date/time</h3><p className="mt-1 text-xs text-[#37414a]">{summary.important_datetime}</p></div><div><h3 className="text-[10px] font-bold uppercase tracking-wide text-[#8b6970]">Required action</h3><p className="mt-1 text-xs text-[#37414a]">{summary.required_action}</p></div></div></div>}</section>;
}
