import Link from "next/link";
import { Bell, ExternalLink, Paperclip, Search } from "lucide-react";

const OFFICIAL_NOTICE_URL = "https://www.cityuniversity.ac.bd/all-notice";

export function NoticesList({ notices, query, category, error }) {
  return <main className="mx-auto max-w-5xl px-4 py-8 sm:px-7"><div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><Link href="/dashboard" className="text-xs text-[#c8102e]">Campus Pulse</Link><p className="mt-4 text-[10px] font-bold uppercase tracking-[.16em] text-[#a13e4c]">City University updates</p><h1 className="mt-1 text-3xl font-semibold text-[#202a35]">Notices</h1></div><Link href="/admin/notices" className="rounded-xl border border-[#e3e3de] bg-white px-4 py-2.5 text-xs font-semibold text-[#c8102e]">Manage notices</Link></div>
    <aside className="mb-5 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-[#ead9b6] bg-[#fffaf0] p-4"><p className="max-w-2xl text-xs leading-5 text-[#665638]">For the latest deadlines, calendar changes, and official announcements, check City University’s live notice board. CampusOS notices may not include every university update.</p><a href={OFFICIAL_NOTICE_URL} target="_blank" rel="noreferrer" className="inline-flex min-h-9 shrink-0 items-center gap-2 rounded-lg border border-[#ead9b6] bg-white px-3 text-xs font-semibold text-[#5c4b2e]">Official notice board <ExternalLink size={14}/></a></aside>
    <form action="/notices" className="mb-5 grid gap-2 rounded-2xl border border-[#e8e8e4] bg-white p-3 sm:grid-cols-[1fr_180px_auto]"><label className="relative"><span className="sr-only">Search notices</span><Search size={16} className="absolute left-3 top-3 text-[#899198]"/><input name="q" defaultValue={query} placeholder="Search notices…" className="h-10 w-full rounded-lg border border-[#e3e3de] pl-9 pr-3 text-sm outline-none focus:border-[#c8102e]"/></label><label><span className="sr-only">Filter by category</span><select name="category" defaultValue={category} className="h-10 w-full rounded-lg border border-[#e3e3de] bg-white px-3 text-sm"><option value="">All categories</option>{["Academic","Exams","Registration","Campus","Events","General"].map(item=><option key={item}>{item}</option>)}</select></label><button className="h-10 rounded-lg bg-[#c8102e] px-5 text-sm font-semibold text-white">Filter</button></form>
    {error?<p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</p>:notices.length?<ul className="space-y-3">{notices.map(notice=><li key={notice.id}><Link href={`/notices/${notice.id}`} className="block rounded-2xl border border-[#e8e8e4] bg-white p-5 hover:border-[#e6bfc5]"><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-[10px] font-semibold uppercase tracking-wide text-[#c8102e]">{notice.category}</span><div className="flex items-center gap-2">{notice.attachment_count>0&&<span className="inline-flex items-center gap-1 rounded-full bg-[#f9eff0] px-2.5 py-1 text-[10px] font-medium text-[#a50e26]"><Paperclip size={12}/>{notice.attachment_count} file{notice.attachment_count===1?"":"s"}</span>}<span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold uppercase ${notice.priority==="urgent"?"bg-red-50 text-red-800":notice.priority==="important"?"bg-amber-50 text-amber-900":"bg-[#f4f2ee] text-[#68737b]"}`}><Bell size={12} className="mr-1 inline"/>{notice.priority}</span></div></div><h2 className="mt-2 text-base font-semibold text-[#26313a]">{notice.title}</h2><p className="mt-1 line-clamp-2 text-sm leading-6 text-[#697681]">{notice.description}</p><time className="mt-3 block text-[11px] text-[#92999e]">{new Date(notice.published_date).toLocaleDateString("en",{year:"numeric",month:"long",day:"numeric",timeZone:"Asia/Dhaka"})}</time></Link></li>)}</ul>:<div className="rounded-2xl border border-dashed border-[#deded9] bg-white p-10 text-center"><Bell className="mx-auto text-[#aa8c90]"/><h2 className="mt-3 text-sm font-semibold text-[#303a43]">No notices to show</h2><p className="mt-1 text-xs text-[#79838c]">Published university notices will appear here.</p></div>}
  </main>;
}
