import Link from "next/link";
import { ArrowUpRight, ExternalLink, Search, UsersRound } from "lucide-react";

const DSW_CLUBS_URL = "https://www.cityuniversity.ac.bd/dsw";

export function ClubDirectory({ clubs, search, error }) {
    return (
        <main className="mx-auto max-w-7xl px-4 pb-12 pt-7 sm:px-7 sm:pt-9 xl:px-10">
            <div className="mb-7"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#a13e4c]">Meet your campus community</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-[#202a35]">Club Directory</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#697681]">Explore student clubs, find a community, and see what is coming up.</p></div>
            <section aria-labelledby="official-clubs-title" className="mb-5 rounded-2xl border border-[#e9e9e5] bg-white p-5 sm:p-6">
                <div className="flex flex-wrap items-start justify-between gap-3">
                    <div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#a13e4c]">Verified university information</p><h2 id="official-clubs-title" className="mt-1 text-lg font-semibold text-[#202a35]">Central clubs listed by Student Welfare</h2><p className="mt-1 max-w-2xl text-xs leading-5 text-[#697681]">Official DSW-listed clubs are included in the directory below. Visit the university page for the current committee and activity details.</p></div>
                    <a href={DSW_CLUBS_URL} target="_blank" rel="noreferrer" className="inline-flex min-h-9 items-center gap-2 rounded-lg border border-[#e5e3de] px-3 text-xs font-semibold text-[#4d5861] hover:border-[#c8102e] hover:text-[#c8102e]">Official DSW page <ExternalLink size={14}/></a>
                </div>
                <p className="mt-3 text-[10px] text-[#858d92]">Source: <a href={DSW_CLUBS_URL} target="_blank" rel="noreferrer" className="underline underline-offset-2">City University DSW · six central clubs</a></p>
            </section>
            <p className="mb-3 text-xs leading-5 text-[#697681]">Profiles marked as official are based on the DSW list. Other club profiles are student or organizer submissions; verify current committees through the university.</p>
            <form method="get" action="/clubs" className="rounded-2xl border border-[#e9e9e5] bg-white p-4"><div className="flex flex-col gap-2 sm:flex-row"><label className="flex min-h-12 min-w-0 flex-1 items-center gap-3 rounded-xl border border-[#e2e0da] px-3.5 focus-within:border-[#a54756] focus-within:ring-2 focus-within:ring-[#c8102e]/10"><Search size={17} className="shrink-0 text-[#8a9297]" aria-hidden="true"/><span className="sr-only">Search clubs</span><input name="q" defaultValue={search} maxLength={120} placeholder="Search club name or description" className="min-w-0 flex-1 bg-transparent text-sm outline-none"/></label><button className="min-h-11 rounded-xl bg-[#c8102e] px-5 text-xs font-semibold text-white transition-colors hover:bg-[#a50e26]">Search clubs</button></div></form>
            {error ? <div role="alert" className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950">{error}</div> : clubs.length ? <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{clubs.map((club) => <article key={club.id} className="flex flex-col rounded-2xl border border-[#e9e9e5] bg-white p-5"><span className="grid size-11 place-items-center rounded-xl bg-[#fbecef] text-[#c8102e]"><UsersRound size={20} /></span><div className="mt-4 flex flex-wrap items-center gap-2"><h2 className="text-base font-semibold text-[#202a35]">{club.name}</h2>{club.slug?.startsWith("central-") && <span className="rounded-full bg-emerald-50 px-2 py-1 text-[9px] font-semibold text-emerald-800">Official DSW listing</span>}{club.slug === "programming-club" && <span className="rounded-full bg-amber-50 px-2 py-1 text-[9px] font-semibold text-amber-900">Sample profile</span>}</div><p className="mt-2 flex-1 text-xs leading-relaxed text-[#74808a]">{club.short_description || club.description}</p>{club.slug?.startsWith("central-") && <a href={DSW_CLUBS_URL} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-[10px] font-semibold text-[#a13e4c]">Official DSW source <ExternalLink size={12}/></a>}<p className="mt-4 text-[10px] text-[#858d92]">{club.upcoming_event_count} upcoming event{Number(club.upcoming_event_count) === 1 ? "" : "s"}</p><Link href={`/clubs/${club.slug}`} className="mt-4 inline-flex min-h-10 items-center justify-between rounded-xl border border-[#e7e4df] px-3.5 text-xs font-semibold text-[#c8102e]">Club details <ArrowUpRight size={15} /></Link></article>)}</div> : <section className="mt-5 rounded-2xl border border-dashed border-[#deded9] bg-white px-5 py-10 text-center"><UsersRound size={22} className="mx-auto text-[#c8102e]" /><h2 className="mt-4 text-base font-semibold text-[#202a35]">{search ? "No clubs match that search" : "No clubs are listed yet"}</h2><p className="mt-2 text-sm text-[#73808a]">{search ? "Try another club name or search term." : "Club profiles will appear here when they are added to CampusOS."}</p></section>}
        </main>
    );
}
