"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
const statuses=["Submitted","Reviewing","In Progress","Resolved"];
const badge={Submitted:"bg-slate-100 text-slate-700",Reviewing:"bg-blue-50 text-blue-800","In Progress":"bg-amber-50 text-amber-900",Resolved:"bg-emerald-50 text-emerald-900"};

export function ComplaintCenter({complaints,isAdmin,error}){
  const router=useRouter();const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [formError,setFormError]=useState("");
  async function submit(event){event.preventDefault();const formElement=event.currentTarget;setBusy(true);setFormError("");setMessage("");const form=new FormData(formElement);try{const supabase=createClient();const {data:{user},error:authError}=await supabase.auth.getUser();if(authError||!user)throw new Error("Your session expired. Sign in again.");const {error:insertError}=await supabase.from("complaints").insert({category:String(form.get("category")),description:String(form.get("description")||"").trim(),user_id:user.id});if(insertError)throw insertError;formElement.reset();setMessage("Your complaint was submitted privately.");router.refresh();}catch(caught){setFormError(caught.message||"The complaint could not be submitted.");}finally{setBusy(false);}}
  async function updateStatus(id,status){setBusy(true);setFormError("");setMessage("");try{const {data,error:updateError}=await createClient().from("complaints").update({status}).eq("id",id).select("id").maybeSingle();if(updateError)throw updateError;if(!data?.id)throw new Error("No complaint was updated. Refresh the page and confirm your admin permissions.");setMessage("Complaint status updated.");router.refresh();}catch(caught){setFormError(caught.message||"Status could not be updated.");}finally{setBusy(false);}}
  return <main className="mx-auto max-w-5xl px-4 py-8 sm:px-7"><a href="/dashboard" className="text-xs text-[#c8102e]">Campus Pulse</a><div className="mt-4 flex flex-wrap items-end justify-between gap-3"><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-[#a13e4c]">Private student support</p><h1 className="mt-1 text-3xl font-semibold text-[#202a35]">Complaint Box</h1><p className="mt-2 text-sm text-[#5e6a74]">Submit an issue and track its progress. Only you and authorized campus admins can view it.</p></div>{isAdmin&&<span className="rounded-full bg-[#f9eff0] px-3 py-1 text-xs font-semibold text-[#c8102e]">Admin review</span>}</div>
    {message&&<p role="status" className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900">{message}</p>}{formError&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-800">{formError}</p>}
    {!isAdmin&&<form onSubmit={submit} className="mt-5 space-y-3 rounded-2xl border border-[#e8e8e4] bg-white p-5"><h2 className="font-semibold">Submit a complaint</h2><label className="block text-xs">Category<select name="category" className="mt-1 h-11 w-full rounded-lg border bg-white px-3 text-sm sm:max-w-sm">{["Facilities","Academic","Transport","Safety","IT Support","Other"].map(item=><option key={item}>{item}</option>)}</select></label><label className="block text-xs">Describe the issue<textarea name="description" required minLength={20} maxLength={5000} rows={5} placeholder="Include relevant details. Do not include passwords or sensitive personal information." className="mt-1 w-full rounded-lg border p-3 text-sm"/></label><button disabled={busy} className="min-h-11 rounded-xl bg-[#c8102e] px-5 text-sm font-semibold text-white disabled:opacity-50">{busy?"Submitting…":"Submit privately"}</button></form>}
    <section className="mt-8"><h2 className="text-lg font-semibold">{isAdmin?"All submitted complaints":"Your complaints"}</h2>{error?<p role="alert" className="mt-3 rounded-xl bg-red-50 p-4 text-sm text-red-800">{error}</p>:complaints.length?<ul className="mt-3 space-y-3">{complaints.map(complaint=><li key={complaint.id} className="rounded-2xl border border-[#e8e8e4] bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-xs font-semibold text-[#c8102e]">{complaint.category}</span><span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${badge[complaint.status]||badge.Submitted}`}>{complaint.status}</span></div><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-[#48545d]">{complaint.description}</p><div className="mt-3 flex flex-wrap items-center justify-between gap-2"><time className="text-[11px] text-[#5e6a74]">Submitted {new Date(complaint.submitted_at).toLocaleString("en",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Dhaka"})}</time>{isAdmin&&<label className="text-xs">Update status<select disabled={busy} value={complaint.status} onChange={event=>updateStatus(complaint.id,event.target.value)} className="ml-2 h-9 rounded-lg border bg-white px-2"><option>Submitted</option><option>Reviewing</option><option>In Progress</option><option>Resolved</option></select></label>}</div></li>)}</ul>:<div className="mt-3 rounded-2xl border border-dashed border-[#deded9] bg-white p-8 text-center text-sm text-[#5e6a74]">{isAdmin?"No complaints have been submitted.":"You have not submitted any complaints yet."}</div>}</section>
  </main>;
}
